language: go
go:
- 1.7
- 1.8
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - master
install:
- go get golang.org/x/net/html
- go get github.com/spf13/cobra
- go get github.com/spf13/viper
- go get github.com/McKael/madon
- go get github.com/ghodss/yaml
- go get github.com/pkg/errors
- go get github.com/kr/text
- go get github.com/m0t0k1ch1/gomif
- go get github.com/mattn/go-isatty
- go get github.com/stretchr/testify/assert
